### ISSUE TITLE
fail installing on kibana 5.0

### ISSUE THREAD

**Issue by agonen** [DeanF/health_metric_vis#1]
root@master1:~/amihay# /data/elasticsearch50/kibana-5.0.0-linux-x86_64/bin/kibana-plugin install https://github.com/DeanF/health_metric_vis/archive/master.zip
Attempting to transfer from https://github.com/DeanF/health_metric_vis/archive/master.zip
Transferring 38802 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by DeanF** [comment]
I believe it's working now. Try the new command line in README.

**Comment by agonen** [comment]
installation was fine  . thanks. 

I'll play with it now
