### ISSUE TITLE
 Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/sr                                                c/ui/public/template_vis_type/template_vis_type

### ISSUE THREAD

**Issue by gpluck73** [DeanF/health_metric_vis#2]
I'm getting the following error when trying to install;

Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in /opt/kibana/installedPlugins/health_metric_vis/public/health_metric                                            _vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/sr                                            c/ui/public/template_vis_type/template_vis_type in /opt/kibana/installedPlugins/                                            health_metric_vis/public
     @ /opt/kibana/installedPlugins/health_metric_vis/public/health_metric_vis.j                                            s 13:44-93

    ERROR in /opt/kibana/installedPlugins/health_metric_vis/public/health_metric                                            _vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/sr                                            c/ui/public/vis/schemas in /opt/kibana/installedPlugins/health_metric_vis/public
     @ /opt/kibana/installedPlugins/health_metric_vis/public/health_metric_vis.j                                            s 17:20-45
"
asosesadmin@asos-es-nonprod-kibana1:~$ ERROR in /opt/kibana/installedPlugins/health_metric_vis/public/health_metric                                            _vis.js
ERROR: command not found

I'm using Kibana 4.4.1.

**Comment by DeanF** [comment]
@gpluck73 Was this resolved?

**Comment by gpluck73** [comment]
yes, I tried using the latest version and whaddya know, it worked like a charm!
